In [8]:
# information available on https://github.com/zestai/zrp/blob/main/README.md
#  if there are problems with pip install zrp: 
#1. Clone this respository https://github.com/zestai/zrp locally on your python packages directory : /opt/anaconda3/lib/python3.9/site-packages 
#2. extract the folder named zrp and follow this instructions https://github.com/zestai/zrp/blob/main/troubleshooting_help.rst

# Libraries

In [71]:
%load_ext autoreload
%autoreload 2
%config Completer.use_jedi=False
from os.path import join, expanduser
import pandas as pd
import sys
import os
import shutil
import re
import warnings

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [72]:
from zrp import ZRP
from zrp.prepare.utils import load_file, load_json

In [73]:
from zrp import ZRP
from zrp.modeling import ZRP_Build
from zrp.prepare.utils import load_file

### ZRP model test sample

In [51]:
warnings.filterwarnings(action='ignore')
home = expanduser('~')
src_path = os.getcwd()
root = os.path.join(src_path, "")
sys.path.append(src_path)

In [58]:
input_sample = load_file(root + "sm_1.csv")
input_sample['ZEST_KEY'] = input_sample.index.astype(str)

In [59]:
input_sample

,ZEST_KEY,first_name,middle_name,last_name,house_number,street_address,city,state,zip_code,original_race,race,original_sex,sex,age
0,0,SAM,T,JONES,121,GRAYS MARKET RD,EARLY BRANCH,SC,29916,WHITE,WHITE,FEMALE,FEMALE,19
1,1,HENRY,NaN,NGO,632,SANDBAR PT,CLOVER,SC,29710,ASIAN,AAPI,MALE,MALE,32
2,2,GABBY,L,BRIDGES,605,KERSHAW ST,CHERAW,SC,29520,WHITE,WHITE,FEMALE,FEMALE,50
3,3,JAMES,M,HORN,3401,DUNCAN ST,COLUMBIA,SC,29205,WHITE,WHITE,MALE,MALE,26
4,4,LONDON,Z,ABARA,26,PECAN CIR,YORK,SC,29745,BLACK/AFRICAN,BLACK,FEMALE,FEMALE,22
5,5,AMY,S,LOCKLEAR,703,WELLS ST,BENNETTSVILLE,SC,29512,AMERICANINDIAN,AIAN,FEMALE,FEMALE,31

In [61]:
%%time
zest_race_predictor = ZRP_Build(zrp_model_name='test_model_small_data') 
zest_race_predictor.fit()

CPU times: user 68 µs, sys: 1 µs, total: 69 µs
Wall time: 76.1 µs

In [63]:
input_sample

,ZEST_KEY,first_name,middle_name,last_name,house_number,street_address,city,state,zip_code,original_race,race,original_sex,sex,age
0,0,SAM,T,JONES,121,GRAYS MARKET RD,EARLY BRANCH,SC,29916,WHITE,WHITE,FEMALE,FEMALE,19
1,1,HENRY,NaN,NGO,632,SANDBAR PT,CLOVER,SC,29710,ASIAN,AAPI,MALE,MALE,32
2,2,GABBY,L,BRIDGES,605,KERSHAW ST,CHERAW,SC,29520,WHITE,WHITE,FEMALE,FEMALE,50
3,3,JAMES,M,HORN,3401,DUNCAN ST,COLUMBIA,SC,29205,WHITE,WHITE,MALE,MALE,26
4,4,LONDON,Z,ABARA,26,PECAN CIR,YORK,SC,29745,BLACK/AFRICAN,BLACK,FEMALE,FEMALE,22
5,5,AMY,S,LOCKLEAR,703,WELLS ST,BENNETTSVILLE,SC,29512,AMERICANINDIAN,AIAN,FEMALE,FEMALE,31

In [64]:
output = zest_race_predictor.transform(input_sample)

  0%|                                                     | 0/1 [00:00<?, ?it/s]
  0%|                                                     | 0/6 [00:00<?, ?it/s][Parallel(n_jobs=-1)]: Using backend ThreadingBackend with 4 concurrent workers.
100%|████████████████████████████████████████████| 6/6 [00:00<00:00, 363.44it/s]

####################################
Processing rows: 0:25000
####################################
Data is loaded
   [Start] Validating input data
     Number of observations: 6
     Is key unique: True
       (Warning!!) middle_name is 16.666666666666664% missing
Directory already exists
   [Completed] Validating input data

   Formatting P1
   Formatting P2
   reduce whitespace

[Start] Preparing geo data

  The following states are included in the data: ['SC']
   ... on state: SC

   Data is loaded
   [Start] Processing geo data
      ...address cleaning
      ...replicating address
         ...Base
         ...Number processing...
         House number dataframe expansion is complete! (n=6)
         ...Base
         ...Map street suffixes...

[Parallel(n_jobs=-1)]: Done   6 out of   6 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=-1)]: Done   6 out of   6 | elapsed:    0.0s finished

         ...Mapped & split by street suffixes...
         ...Number processing...

         Address dataframe expansion is complete! (n=7)
      ...formatting
   [Completed] Processing geo data
   [Start] Mapping geo data
      ...merge user input & lookup table

100%|█████████████████████████████████████████████| 1/1 [00:04<00:00,  4.18s/it]

      ...mapping
   [Completed] Validating input geo data
Directory already exists
...Output saved
   [Completed] Mapping geo data

[Completed] Preparing geo data

[Start] Preparing ACS data
   [Start] Validating ACS input data
     Number of observations: 6
     Is key unique: True
       (Warning!!) middle_name is 16.666666666666664% missing

   [Completed] Validating ACS input data

   ...loading ACS lookup tables

   ... combining ACS & user input data
 ...Copy dataframes
 ...Block group
 ...Census tract
 ...Zip code
 ...No match
 ...Merge
 ...Merging complete
[Complete] Preparing ACS data

=========================
BUILDING block_group MODEL.
=========================

Directory already exists
Dropping ['census_tract', 'zip_code'] features
    ...Len features to keep list:  98
    ...Data shape pre feature drop:  (16, 198)
    ...Data shape post feature drop:  (16, 97)
Directory already exists
...Output saved
...Output saved
...Output saved
...Output saved
Post-sampling shape:  (6, 14)


Unique train labels:  ['BLACK' 'WHITE' 'AIAN']
Unique test labels:  ['AIAN' 'WHITE']

---
Saving raw data
...Output saved
...Output saved

---
Building pipeline

---
Fitting pipeline
[Pipeline] ..... (step 1 of 8) Processing Drop Features, total=   0.0s
Pass through
[Pipeline] .. (step 2 of 8) Processing Compound Name FE, total=   0.0s

  0%|                                                     | 0/1 [00:00<?, ?it/s][Parallel(n_jobs=-1)]: Using backend ThreadingBackend with 4 concurrent workers.
100%|███████████████████████████████████████████| 1/1 [00:00<00:00, 1179.50it/s]

[Pipeline] ............ (step 3 of 8) Processing App FE, total=   0.3s
[Pipeline] ............ (step 4 of 8) Processing ACS FE, total=   0.1s
[Pipeline] .. (step 5 of 8) Processing Name Aggregation, total=   0.1s
[Pipeline] . (step 6 of 8) Processing Drop Features (2), total=   0.0s
[Pipeline] ............ (step 7 of 8) Processing Impute, total=   0.0s

[Parallel(n_jobs=-1)]: Done   1 out of   1 | elapsed:    0.0s finished

[Pipeline]  (step 8 of 8) Processing Correlated Feature Selection, total=   0.1s
Directory already exists

---
Transforming FE data
Pass through

  0%|                                                     | 0/1 [00:00<?, ?it/s][Parallel(n_jobs=-1)]: Using backend ThreadingBackend with 4 concurrent workers.
100%|███████████████████████████████████████████| 1/1 [00:00<00:00, 3216.49it/s]
[Parallel(n_jobs=-1)]: Done   1 out of   1 | elapsed:    0.0s finished

---
Saving FE data
...Output saved

---
building zrp_model

---
fitting zrp_model

ValueError: Invalid classes inferred from unique values of `y`.  Expected: [0 1 2], got ['AIAN' 'BLACK' 'WHITE']

### ZRP model test full dataset

In [74]:
## full dataset
nj_mayors = load_file(src_path + "/2022-nj-mayors.csv")
nj_mayors.shape

(565, 18)

In [75]:
zrp_sample = pd.DataFrame(columns=['first_name', 'middle_name', 'last_name', 'house_number', 'street_address', 'city', 'state', 'zip_code'])
split_mayor_names = nj_mayors['MAYOR NAME'].str.split(' ')
zrp_sample['first_name'] = split_mayor_names.str[0]
zrp_sample['last_name'] = split_mayor_names.str[-1]
zrp_sample['city'] = nj_mayors['CITY']
zrp_sample['state'] = nj_mayors['STATE']
zrp_sample['zip_code'] = nj_mayors['ZIP']
zrp_sample['house_number'] = nj_mayors['ADDRESS 1'].str.extract('([0-9]+)')
zrp_sample['street_address'] = nj_mayors['ADDRESS 1'].str.extract('.*[0-9]+([^0-9]+)')
zrp_sample['ZEST_KEY'] = zrp_sample.index.astype(str)  #must specify key to establish correspondence between inputs and outputs
zrp_sample

,first_name,middle_name,last_name,house_number,street_address,city,state,zip_code,ZEST_KEY
0,Fred,NaN,Tagliarini,NaN,NaN,Aberdeen,NJ,07747-2300,0
1,Kimberly,NaN,Horton,NaN,NaN,Absecon,NJ,08201,1
2,Gabe,NaN,Plumer,782,Frenchtown Road,Milford,NJ,08848,2
3,Rosemary,NaN,Tuohy,NaN,NaN,Allamuchy,NJ,07820,3
4,Ari,NaN,Bernstein,500,West Crescent Avenue,Allendale,NJ,07401,4
...,...,...,...,...,...,...,...,...,...
560,Paul,NaN,Sarlo,85,Humboldt Street,Wood-Ridge,NJ,07075-2344,560
561,Donald,NaN,Dietrich,286,NaN,Woodstown,NJ,08098,561
562,Craig,NaN,Frederick,120,Village Green Drive,Woolwich Township,NJ,08085-3180,562
563,Donald,NaN,Cottrell,21,Saylors Pond Road,Wrightstown,NJ,08562,563
564,Rudolf,NaN,Boonstra,NaN,NaN,Wyckoff,NJ,07481,564

In [77]:
## Cleanup the directory structure 
if os.path.exists('artifacts'):
    shutil.rmtree('artifacts')

In [78]:
%%time
zest_race_predictor = ZRP(runname='custom_outputs') 
zest_race_predictor.fit()
zrp_output = zest_race_predictor.transform(zrp_sample)

  0%|                                                     | 0/1 [00:00<?, ?it/s]
  0%|                                                   | 0/565 [00:00<?, ?it/s]

####################################
Processing rows: 0:25000
####################################
Data is loaded
   [Start] Validating input data
     Number of observations: 565
     Is key unique: True
       (Warning!!) street_address is 18.230088495575224% missing
       (Warning!!) middle_name is 100.0% missing
       (Warning!!) house_number is 11.327433628318584% missing
Directory already exists
   [Completed] Validating input data

   Formatting P1
   Formatting P2
   reduce whitespace

[Start] Preparing geo data

  The following states are included in the data: ['NJ']
   ... on state: NJ

   Data is loaded
   [Start] Processing geo data
      ...address cleaning

[Parallel(n_jobs=-1)]: Using backend ThreadingBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done  42 tasks      | elapsed:    0.0s
[Parallel(n_jobs=-1)]: Done 192 tasks      | elapsed:    0.0s
[Parallel(n_jobs=-1)]: Done 442 tasks      | elapsed:    0.1s
100%|███████████████████████████████████████| 565/565 [00:00<00:00, 6521.01it/s]
[Parallel(n_jobs=-1)]: Done 565 out of 565 | elapsed:    0.1s finished

      ...replicating address
         ...Base
         ...Number processing...
         House number dataframe expansion is complete! (n=629)
         ...Base
         ...Map street suffixes...
         ...Mapped & split by street suffixes...
         ...Number processing...

         Address dataframe expansion is complete! (n=1067)
      ...formatting
   [Completed] Processing geo data
   [Start] Mapping geo data
      ...merge user input & lookup table
      ...mapping

100%|█████████████████████████████████████████████| 1/1 [00:08<00:00,  8.65s/it]

   [Completed] Validating input geo data
Directory already exists
...Output saved
   [Completed] Mapping geo data

[Completed] Preparing geo data

[Start] Preparing ACS data
   [Start] Validating ACS input data
     Number of observations: 565
     Is key unique: True
       (Warning!!) street_address is 18.230088495575224% missing
       (Warning!!) middle_name is 100.0% missing

   [Completed] Validating ACS input data

   ...loading ACS lookup tables

   ... combining ACS & user input data
 ...Copy dataframes
 ...Block group
 ...Census tract
 ...Zip code
 ...No match
 ...Merge
 ...Merging complete
[Complete] Preparing ACS data

   [Start] Validating pipeline input data
     Number of observations: 1556
     Is key unique: False
       (Warning!!) street_address is 12.853470437017995% missing
       (Warning!!) middle_name is 100.0% missing
   [Completed] Validating pipeline input data

  0%|                                                     | 0/1 [00:00<?, ?it/s][Parallel(n_jobs=-1)]: Using backend ThreadingBackend with 4 concurrent workers.
100%|███████████████████████████████████████████| 1/1 [00:00<00:00, 1371.58it/s]
[Parallel(n_jobs=-1)]: Done   1 out of   1 | elapsed:    0.0s finished
  0%|                                                     | 0/1 [00:00<?, ?it/s][Parallel(n_jobs=-1)]: Using backend ThreadingBackend with 4 concurrent workers.
100%|████████████████████████████████████████████| 1/1 [00:00<00:00, 834.19it/s]
[Parallel(n_jobs=-1)]: Done   1 out of   1 | elapsed:    0.0s finished
  0%|                                                     | 0/1 [00:00<?, ?it/s][Parallel(n_jobs=-1)]: Using backend ThreadingBackend with 4 concurrent workers.
100%|███████████████████████████████████████████| 1/1 [00:00<00:00, 3226.39it/s]
[Parallel(n_jobs=-1)]: Done   1 out of   1 | elapsed:    0.0s finished
  0%|                                                     | 0/1 [00:00<?, ?it/s][Parallel(n_jobs=-1)]: Using backend ThreadingBackend with 4 concurrent workers.
100%|███████████████████████████████████████████| 1/1 [00:00<00:00, 2941.31it/s]
[Parallel(n_jobs=-1)]: Done   1 out of   1 | elapsed:    0.0s finished

   ...Proxies generated
...Output saved
...Output saved
CPU times: user 1min 2s, sys: 9.88 s, total: 1min 12s
Wall time: 1min 14s

In [79]:
zrp_output

,first_name,middle_name,last_name,house_number,street_address,city,state,zip_code,ZEST_KEY,AAPI,AIAN,BLACK,HISPANIC,WHITE,race_proxy,source_zrp_block_group,source_zrp_census_tract,source_zrp_zip_code,source_bisg,source_zrp_name_only
0,Fred,NaN,Tagliarini,NaN,NaN,Aberdeen,NJ,07747-2300,0,0.000445,0.000366,0.001628,0.000926,0.996634,WHITE,0.0,0.0,1.0,0.0,0.0
1,Kimberly,NaN,Horton,NaN,NaN,Absecon,NJ,08201,1,0.020371,0.022385,0.363590,0.042607,0.551046,WHITE,0.0,0.0,1.0,0.0,0.0
2,Gabe,NaN,Plumer,782,Frenchtown Road,Milford,NJ,08848,2,0.000117,0.000096,0.031971,0.002676,0.965141,WHITE,1.0,0.0,0.0,0.0,0.0
3,Rosemary,NaN,Tuohy,NaN,NaN,Allamuchy,NJ,07820,3,0.000583,0.000500,0.001106,0.002331,0.995479,WHITE,0.0,0.0,1.0,0.0,0.0
4,Ari,NaN,Bernstein,500,West Crescent Avenue,Allendale,NJ,07401,4,0.016766,0.008396,0.002317,0.049893,0.922627,WHITE,0.0,0.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
560,Paul,NaN,Sarlo,85,Humboldt Street,Wood-Ridge,NJ,07075-2344,560,0.000533,0.000352,0.000895,0.000873,0.997347,WHITE,0.0,0.0,1.0,0.0,0.0
561,Donald,NaN,Dietrich,286,NaN,Woodstown,NJ,08098,561,0.009935,0.000523,0.007084,0.008390,0.974068,WHITE,0.0,0.0,1.0,0.0,0.0
562,Craig,NaN,Frederick,120,Village Green Drive,Woolwich Township,NJ,08085-3180,562,0.012613,0.018596,0.191353,0.023612,0.753826,WHITE,0.0,0.0,1.0,0.0,0.0
563,Donald,NaN,Cottrell,21,Saylors Pond Road,Wrightstown,NJ,08562,563,0.005893,0.011369,0.025073,0.010588,0.947076,WHITE,1.0,0.0,0.0,0.0,0.0
564,Rudolf,NaN,Boonstra,NaN,NaN,Wyckoff,NJ,07481,564,0.000923,0.000636,0.001297,0.025040,0.972104,WHITE,0.0,0.0,1.0,0.0,0.0

In [80]:
zrp_sample

,first_name,middle_name,last_name,house_number,street_address,city,state,zip_code,ZEST_KEY
0,Fred,NaN,Tagliarini,NaN,NaN,Aberdeen,NJ,07747-2300,0
1,Kimberly,NaN,Horton,NaN,NaN,Absecon,NJ,08201,1
2,Gabe,NaN,Plumer,782,Frenchtown Road,Milford,NJ,08848,2
3,Rosemary,NaN,Tuohy,NaN,NaN,Allamuchy,NJ,07820,3
4,Ari,NaN,Bernstein,500,West Crescent Avenue,Allendale,NJ,07401,4
...,...,...,...,...,...,...,...,...,...
560,Paul,NaN,Sarlo,85,Humboldt Street,Wood-Ridge,NJ,07075-2344,560
561,Donald,NaN,Dietrich,286,NaN,Woodstown,NJ,08098,561
562,Craig,NaN,Frederick,120,Village Green Drive,Woolwich Township,NJ,08085-3180,562
563,Donald,NaN,Cottrell,21,Saylors Pond Road,Wrightstown,NJ,08562,563
564,Rudolf,NaN,Boonstra,NaN,NaN,Wyckoff,NJ,07481,564

### ZRP model bisg dataset

In [ ]:
nj_mayors = load_file(src_path + "/2022-nj-mayors.csv")
nj_mayors.shape